fix: removed debian configuration requirements

diff --git a/templates/default/service_tomee.erb b/templates/default/service_tomee.erb
--- a/templates/default/service_tomee.erb
+++ b/templates/default/service_tomee.erb
@@ -32,14 +32,6 @@ if [ -r /etc/default/locale ]; then
 	. /etc/default/locale
 	export LANG
 fi
-
-. /lib/lsb/init-functions
-
-if [ -r /etc/default/rcS ]; then
-	. /etc/default/rcS
-fi
-
-
 # The following variables can be overwritten in $ENV_TOMEE
 
 # Run Tomcat 7 as this user ID and group ID
@@ -73,12 +65,12 @@ if [ -f "$ENV_TOMEE" ]; then
 fi
 
 if [ ! -d "$CATALINA_BASE/conf" ]; then
-  log_failure_msg "invalid CATALINA_BASE: $CATALINA_BASE"
+  echo "invalid CATALINA_BASE: $CATALINA_BASE"
   exit 1
 fi
 
 if [ ! -f "$CATALINA_HOME/bin/bootstrap.jar" ]; then
-	log_failure_msg "$NAME is not installed"
+	echo "$NAME is not installed"
 	exit 1
 fi
 
@@ -97,35 +89,42 @@ if [ -z "${JSSE_HOME}" -a -r "${JAVA_HOME}/jre/lib/jsse.jar" ]; then
 fi
 
 catalina_sh() {
-  $DAEMON_TOMEE $1
-	status="$?"
-	set +a -e
-	return $status
+  if [ 'stop' = $1 ]; then
+    if [ -s /opt/tomee/logs/catalina-daemon.pid ]; then
+      $DAEMON_TOMEE $1
+    else
+      echo "Warning file /opt/tomee/logs/catalina-daemon.pid empty. Already stopped?"
+    fi
+  else
+    $DAEMON_TOMEE $1
+  fi
+  status="$?"
+  set +a -e
+  return $status
 }
 
 case "$1" in
   start)
 	if [ -z "$JAVA_HOME" ]; then
-		log_failure_msg "no JDK or JRE found - please set JAVA_HOME"
+		echo "no JDK or JRE found - please set JAVA_HOME"
 		exit 1
 	fi
 
 	if [ ! -d "$CATALINA_BASE/conf" ]; then
-		log_failure_msg "invalid CATALINA_BASE: $CATALINA_BASE"
+		echo "invalid CATALINA_BASE: $CATALINA_BASE"
 		exit 1
 	fi
 
-	  log_daemon_msg "Starting $DESC" "$NAME"
+	 echo "Starting $DESC" "$NAME"
    set +e
    catalina_sh start
    set -e
 	;;
   stop)
-	  log_daemon_msg "Stopping $DESC" "$NAME"
+	echo "Stopping $DESC" "$NAME"
 
 	set +e
   catalina_sh stop
-	log_end_msg 0
 	set -e
 	;;
    status)
@@ -141,7 +140,7 @@ case "$1" in
     set -e
         ;;
   *)
-	log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
+	echo "Usage: $0 {start|stop|restart|force-reload|status}"
 	exit 1
 	;;
 esac
