fixed centos provisioning removed jsvc (jsvc under centos have a different behavior) fixed default configuration

diff --git a/templates/default/service_tomee.erb b/templates/default/service_tomee.erb
--- a/templates/default/service_tomee.erb
+++ b/templates/default/service_tomee.erb
@@ -16,37 +16,25 @@
 set -e
 
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
-NAME=tomee
+NAME=<%= @instance %>
+SHUTDOWN_TIMEOUT=30 # n. retries * 10 seconds
 DESC="Tomee"
-ENV_TOMEE="/opt/<%= @instance %>/bin/setenv.sh"
-DAEMON_TOMEE="/opt/<%= @instance %>/bin/daemon.sh"
-JVM_TMP="/tmp/<%= @instance %>-tmp"
+ENV_TOMEE="<%= @base %>/bin/setenv.sh"
+DAEMON_TOMEE="<%= @base %>/bin/catalina.sh"
+
+JVM_TMP="/tmp"
 
 if [ `id -u` -ne 0 ]; then
-	echo "You need root privileges to run this script"
-	exit 1
+  echo "You need root privileges to run this script"
+  exit 1
 fi
  
 # Make sure tomee is started with system locale
 if [ -r /etc/default/locale ]; then
-	. /etc/default/locale
-	export LANG
+  . /etc/default/locale
+  export LANG
 fi
 # The following variables can be overwritten in $ENV_TOMEE
-
-# Run Tomcat 7 as this user ID and group ID
-TOMCAT_USER=tomcat7
-TOMCAT_GROUP=tomcat7
-
-
-# Directory where the Tomcat 6 binary distribution resides
-CATALINA_HOME=/usr/share/$NAME
-
-# Directory for per-instance configuration files and webapps
-CATALINA_BASE=/var/lib/$NAME
-
-# Use the Java security manager? (yes/no)
-TOMCAT_SECURITY=no
 
 # Default Java options
 # Set java.awt.headless=true if JAVA_OPTS is not set so the
@@ -54,14 +42,17 @@ TOMCAT_SECURITY=no
 # It also looks like the default heap size of 64M is not enough for most cases
 # so the maximum heap size is set to 128M
 if [ -z "$JAVA_OPTS" ]; then
-	JAVA_OPTS="-Djava.awt.headless=true -Xmx128M"
+  JAVA_OPTS="-Djava.awt.headless=true -Xmx128M"
 fi
 
 # End of variables that can be overwritten in $ENV_TOMEE
 
 # overwrite settings from default file
 if [ -f "$ENV_TOMEE" ]; then
-	. "$ENV_TOMEE"
+  . "$ENV_TOMEE"
+else
+  echo "Env configuration not found, file $ENV_TOMEE missing."
+  exit 1
 fi
 
 if [ ! -d "$CATALINA_BASE/conf" ]; then
@@ -70,17 +61,17 @@ if [ ! -d "$CATALINA_BASE/conf" ]; then
 fi
 
 if [ ! -f "$CATALINA_HOME/bin/bootstrap.jar" ]; then
-	echo "$NAME is not installed"
-	exit 1
+  echo "$NAME is not installed"
+  exit 1
 fi
 
 if [ -z "$CATALINA_TMPDIR" ]; then
-	CATALINA_TMPDIR="$JVM_TMP"
+  CATALINA_TMPDIR="$JVM_TMP"
 fi
 
 # Set the JSP compiler if set in the tomcat7.default file
 if [ -n "$JSP_COMPILER" ]; then
-	JAVA_OPTS="$JAVA_OPTS -Dbuild.compiler=\"$JSP_COMPILER\""
+  JAVA_OPTS="$JAVA_OPTS -Dbuild.compiler=\"$JSP_COMPILER\""
 fi
 
 # Look for Java Secure Sockets Extension (JSSE) JARs
@@ -88,16 +79,53 @@ if [ -z "${JSSE_HOME}" -a -r "${JAVA_HOME}/jre/lib/jsse.jar" ]; then
     JSSE_HOME="${JAVA_HOME}/jre/"
 fi
 
-catalina_sh() {
-  if [ 'stop' = $1 ]; then
-    if [ -s /opt/tomee/logs/catalina-daemon.pid ]; then
-      $DAEMON_TOMEE $1
-    else
-      echo "Warning file /opt/tomee/logs/catalina-daemon.pid empty. Already stopped?"
-    fi
+if [ ! -f <%= @catalina_pid %> ]; then
+    su - $TOMCAT_USER -c "touch <%= @catalina_pid %>"
+fi
+
+catalina_start() {
+  call_catalina_sh start
+}
+
+catalina_stop() {
+  if [ -s <%= @catalina_pid %> ]; then
+    TEMPFILE=/tmp/$$.<%= @instance %>.counter.tmp
+    touch $TEMPFILE
+    while (true);
+    do 
+      call_catalina_sh stop
+      if [ -s <%= @catalina_pid %> ]; then
+        pid=$(cat <%= @catalina_pid %>)
+      else
+        break;
+      fi
+      COUNTER=$[$(cat $TEMPFILE) + 1]
+      echo $COUNTER > $TEMPFILE
+      ps -p $pid > /dev/null 2>&1
+      if [ $? -ne 0 ]
+      then 
+        echo "Shutted down <%= @instance %> "$pid" (after "$COUNTER" retries)..."
+        break
+      else
+        sleep 10;
+      fi
+      
+  # CHECK FOR TIMEOUT 
+      if [ $COUNTER -gt $SHUTDOWN_TIMEOUT ] 
+      then
+          echo "Warning: Timeout."$COUNTER" Forced shutdown <%= @instance %>"
+          kill -9 $pid
+          rm <%= @catalina_pid %>
+          break;
+      fi
+    done
   else
-    $DAEMON_TOMEE $1
+    echo "Warning file <%= @catalina_pid %> empty. Already stopped?"
   fi
+}
+
+call_catalina_sh() {
+  su - $TOMCAT_USER -c "$DAEMON_TOMEE $1"
   status="$?"
   set +a -e
   return $status
@@ -105,44 +133,44 @@ catalina_sh() {
 
 case "$1" in
   start)
-	if [ -z "$JAVA_HOME" ]; then
-		echo "no JDK or JRE found - please set JAVA_HOME"
-		exit 1
-	fi
+    if [ -z "$JAVA_HOME" ]; then
+      echo "no JDK or JRE found - please set JAVA_HOME"
+      exit 1
+    fi
+  
+    if [ ! -d "$CATALINA_BASE/conf" ]; then
+      echo "invalid CATALINA_BASE: $CATALINA_BASE"
+      exit 1
+    fi
 
-	if [ ! -d "$CATALINA_BASE/conf" ]; then
-		echo "invalid CATALINA_BASE: $CATALINA_BASE"
-		exit 1
-	fi
-
-	 echo "Starting $DESC" "$NAME"
-   set +e
-   catalina_sh start
-   set -e
-	;;
+    echo "Starting $DESC" "$NAME"
+    set +e
+    catalina_start
+    set -e
+    ;;
   stop)
-	echo "Stopping $DESC" "$NAME"
-
-	set +e
-  catalina_sh stop
-	set -e
-	;;
-   status)
-	set +e
-  catalina_sh status
-	set -e
+    echo "Stopping $DESC" "$NAME"
+  
+    set +e
+    catalina_stop
+    set -e
+    ;;
+  status)
+    set +e
+    call_catalina_sh status
+    set -e
         ;;
   restart|force-reload)
     set +e
-    catalina_sh stop
+    catalina_stop
     sleep 1
-    catalina_sh start
+    catalina_start
     set -e
         ;;
   *)
-	echo "Usage: $0 {start|stop|restart|force-reload|status}"
-	exit 1
-	;;
+  echo "Usage: $0 {start|stop|restart|force-reload|status}"
+  exit 1
+  ;;
 esac
 
 exit 0
